### ISSUE TITLE
Is this still maintain?

### ISSUE THREAD

**Issue by rainbatt** [groggyegg/plugin.video.duboku#1]
Like this plugin alot, thanks.  Just wondering if this plugin will be able to work in Kodi19?

**Comment by groggyegg** [comment]
Yes, it's still maintained. Support for Kodi 19 will be added, but it will probably take some time since I'm currently busy with other stuff.

The next release will include custom filter dialog and English language support. Kodi 18 won't be supported moving forward, but old version will still be available in github pages.

**Comment by ameizeing** [comment]
I'm unable to find the zip file for Duboku plugin for Kodi 18. Can you please load it on your front page like that for Dramacool 1.8.5?

**Comment by groggyegg** [comment]
> I'm unable to find the zip file for Duboku plugin for Kodi 18. Can you please load it on your front page like that for Dramacool 1.8.5?

You can find the old version in https://github.com/groggyegg/lime/tree/master/plugin.video.duboku
Currently I am a bit busy with work. I will try to upload it when I have time or during the weekend.
