### ISSUE TITLE
ListItem Not Defined Error

### ISSUE THREAD

**Issue by dazazbab** [groggyegg/plugin.video.duboku#9]
Hi there,

Thanks for the amazing addon. Been using it for a while now until today. 

For some reason Duboku stopped running on my RPi4. The log mentioned 'Name Error' and 'ListItem not defined'. I reinstalled Duboku a few times from your repo but it still wont work. I got Duboku running on my Firestick with no issues.

My RPi is running Libreelec 11.0 and my Firestick is running Kodi 20.

Appreciate the help.

![ListItem Error Duboku](https://user-images.githubusercontent.com/66974089/224529432-0073a23c-2dea-4f9e-8975-da049f78e6aa.png)

**Comment by groggyegg** [comment]
It seems there is some issue with importing ListItem. Hard to know what the cause is from the log and I'm currently working on rewriting the code so I won't have much time to fix it.

I recommend to wait for the release which is due at the end of this month or you can download an early release from this link [plugin.video.duboku](https://github.com/groggyegg/plugin.video.duboku/archive/refs/heads/dev.zip) + [script.module.xbmcext](https://github.com/groggyegg/script.module.xbmcext/archive/refs/heads/duboku/selecttab.zip) but keep in mind that it could be buggy and not every feature exist yet. Once it gets released, older early release need to be uninstalled.

**Comment by dazazbab** [comment]
Thanks. I'll try the link you sent.
